"""Fix events.occured_at Spelling

Revision ID: 4bb4124c8435
Revises: d0d69e463126
Create Date: 2026-02-23 18:01:56.406083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bb4124c8435'
down_revision: Union[str, Sequence[str], None] = 'd0d69e463126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('events', 'occured_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('occured_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('events', 'occurred_at')
    # ### end Alembic commands ###
