"""Update events table; Add services and deployments tables

Revision ID: e33a8930ab69
Revises: f1bec4b2c33e
Create Date: 2026-02-23 13:05:25.148954

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = "e33a8930ab69"
down_revision: Union[str, Sequence[str], None] = "f1bec4b2c33e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deployments",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("image_tag", sa.String(length=7), nullable=False),
        sa.Column(
            "status",
            sa.Enum("STARTED", "SUCCESS", "FAILED", name="deployment_status_enum"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "services",
        sa.Column(
            "id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "events", sa.Column("event_type", sa.String(length=128), nullable=False)
    )
    op.add_column("events", sa.Column("service_id", UUID(as_uuid=True), nullable=False))
    op.add_column(
        "events", sa.Column("deployment_id", UUID(as_uuid=True), nullable=False)
    )
    op.add_column(
        "events",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "events",
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_foreign_key(None, "events", "deployments", ["deployment_id"], ["id"])
    op.create_foreign_key(None, "events", "services", ["service_id"], ["id"])
    op.drop_column("events", "created_at")
    op.drop_column("events", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("type", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    )
    op.add_column(
        "events",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_column("events", "event_data")
    op.drop_column("events", "occurred_at")
    op.drop_column("events", "deployment_id")
    op.drop_column("events", "service_id")
    op.drop_column("events", "event_type")
    op.drop_table("services")
    op.drop_table("deployments")
    # ### end Alembic commands ###
